### ISSUE TITLE
No place to reset password

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#11]
The reset password functionality is implemented in code (hopefully it works), but is not provided in the UI.

The relevant code:
RegistryUserServiceImpl.java
```java
	@Override
	public void requestPasswordReset(String emailAddress) {
```

This issue is to expose this functionality on the login forms (top right hand corner, and full size).

**Comment by phuonghuynh** [comment]
@ronaldtse could we add reset pwd button?

**Comment by ronaldtse** [comment]
Yes @phuonghuynh , thanks!

**Comment by ronaldtse** [comment]
Ping @phuonghuynh

**Comment by maccraymer** [comment]
This issue appears to be completed. There is a “Forgot password” link in the drop down login menu and it opens a web page to reset a user’s password. Why is there no comment on this and why isn’t the issue marked as done and closed?

Also, some other issues are marked as done but not closed. Why not?

**Comment by ronaldtse** [comment]
@maccraymer thanks for the reminder! The only reason some issues were done but not closed is because we forgot to close them 😉

**Comment by phuonghuynh** [comment]
This is done, we can close it now
