### ISSUE TITLE
Add Google Form to solicit feedback

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#13]
The code is shown below:

```html
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScv6B77NasVMxH0zFMxhHC-HPS-GsLR16oBBWcrooq9ANu97A/viewform?embedded=true" width="640" height="832" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
```

This form will automatically send feedback to the geodetic-registry-feedback repository as new issues.

**Comment by phuonghuynh** [comment]
Which page should we add this form?

**Comment by ronaldtse** [comment]
@phuonghuynh we should add a Feedback page like this: https://www.geolexica.com/about/

**Comment by ronaldtse** [comment]
Maybe `geodetic.isotc211.org/feedback`?

**Comment by ronaldtse** [comment]
And this is done. Thanks @phuonghuynh !
