### ISSUE TITLE
bug: ISOGR error importing EVRF2019 spreadsheet

### ISSUE THREAD

**Issue by phuonghuynh** [ISO-TC211/iso-geodetic-registry#143]
Details can be found in email

> Subject: ISOGR error importing EVRF2019 spreadsheet

**Comment by phuonghuynh** [comment]
Debug leads me to "relationship field `justification` is empty/null" ; so this bug related to given data is not correct format.

To fix this, I think we need to update excel sheet for this column, `sheet UoM(UM#) ; col Proposal Justification`

cc @ronaldtse

**Comment by maccraymer** [comment]
Thanks for checking into this Phuong! I did not notice an errant UoM entry that should not have been in the spreadsheet. I removed it and the spreadsheet now imports properly. Sorry for the trouble! I will close this issue now.

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh and @maccraymer ! Sorry that it took so long!
