### ISSUE TITLE
Create new GHA token with write permission

### ISSUE THREAD

**Issue by phuonghuynh** [ISO-TC211/iso-geodetic-registry#147]
To support dispatch release tag and push docker to GitHub registry

**Comment by phuonghuynh** [comment]
ping @ronaldtse ; we need it to release the fix for aws db upgrade

**Comment by ronaldtse** [comment]
@phuonghuynh please help update. Thanks!

**Comment by phuonghuynh** [comment]
> @phuonghuynh please help update. Thanks!

I don't have permission to update setting token ^

**Comment by ronaldtse** [comment]
@phuonghuynh now available at `secrets.ISOGR_CI_PAT_TOKEN`.

**Comment by ronaldtse** [comment]
Please help close when verified. Thanks!

**Comment by phuonghuynh** [comment]
Thanks Ronald, its working, https://github.com/ISO-TC211/iso-geodetic-registry/actions/runs/1794133186
