### ISSUE TITLE
"Superseding" action causes crashes at Registry

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#17]
From @maccraymer :

> I am emailing about further problems with the supercede action in the Registry that I and Dan Roman encountered while trying to revise some of his existing entries. As it stands now, it is not working properly and we are unable to supercede anything.
>  
> 1) The supercede action allows for multiple successor items to be created but which are apparently not editable after saving. When entering a single successor, one must click the “Save proposal” button at the bottom of the entry form (this implies the entire proposal is being saved, not just one successor item). After saving, it is apparently no longer possible to edit the successor items after saving each one! This is before submitting it as a proposal.
>  
> 2) When entering information for a single successor item, parts of the successor entry form do not allow for any input. Specifically, there is no way to enter any citations (information sources) or any proposal details (justification, notes to RM and CB).
>  
> 3) After saving a successor item, the proposal details were available under the Additional Information tab in the overview of the successor items page. Although it was possible to enter text into the Justification and Notes boxes, the information was not saved after clicking the Continue button at the bottom of the page. Going back to the Additional Information tab displayed blank text boxes. There was effectively no way of entering the justification and notes to RM/CB.
>  
> 4) The biggest problem is that the first successor item was not prepopulated with the information from the original item. We had to re-enter *all* of the information again when we only wanted to change three numbers in the original item! This would be especially onerous for the citations, had we been able to enter any! It will take a huge effort to make simple revisions to a few dozen entries. At this point, I would rather have a simpler supercede action similar to the Clarify action where only one successor is allowed an it is prepopulated with the original item’s information. We can deal with multiple successors later. We will need to figure out a way of resolving this problem as there are many revisions to make.
>  
> To end on a positive note, the Clarify action works fine now. The last time I tried selecting it (during our CB meeting at the TC 211 Plenary in Maribor), I got a server error.

**Comment by maccraymer** [comment]
Florian Esser has confirmed this bug was present in the original software that was installed in Norway. Apparently, it has existed for a while. I suggest to keep this issue open until it is fixed in the next maintenance contract with Florian.

**Comment by maccraymer** [comment]
Florian Esser has apparently fixed this bug and it should probably be closed? The link to the pull request that addresses this issues is at https://github.com/ISO-TC211/iso-geodetic-registry/pull/45

**Comment by maccraymer** [comment]
This bug is still present in the staging instance. When I tried to supersede Vertical Datum item 118 Canadian Geodetic Vertical Datum of 2013 (Canadian Gravitmetric Geoid of 2013), I got an HTML 400 error (Bad Request) upon submitting the successor item. I have attached a PDF of the error message.

[2b Supercession HTML Error.pdf](https://github.com/ISO-TC211/iso-geodetic-registry/files/4596751/2b.Supercession.HTML.Error.pdf)

This is a critical function and we would be grateful if this bug can be given the highest priority. There are many Registry entries that need to be corrected (superseded) and we are unable to do it. Thanks!

**Comment by phuonghuynh** [comment]
@maccraymer I did very simple "supersede" action for item 118 by filled-in only required data on the Staging site but I did not get error, could I have data that you used to get this error? It will help me deep dive into this error.


![Screenshot_7](https://user-images.githubusercontent.com/705510/81383144-bab7ea00-9139-11ea-99ab-5bc3f976760b.png)

**Comment by maccraymer** [comment]
The HTTP Status 400 error occurrs only with Safari. Chrome and Firefox work fine. I suggest to keep this bug issue open to eventually resolve the incompatibility with Safari but give it a lower priority. Thanks.

**Comment by maccraymer** [comment]
This appears to have been fixed. I can no longer reproduce the error in Safari. I have closed this issue. Thanks.
