### ISSUE TITLE
Need development instance of registry

### ISSUE THREAD

**Issue by maccraymer** [ISO-TC211/iso-geodetic-registry#18]
We need a development or staging instance of the Registry separate from the production instance. The purpose would be to test and evaluate the functionality of the existing Registry and the implementation of future enhancements without the risk of corrupting the production instance.

**Comment by ronaldtse** [comment]
@maccraymer we're working on this right now. @phuonghuynh is the one responsible at Ribose.

**Comment by phuonghuynh** [comment]
@ronaldtse we supported "env" already, but we did not deploy it. Could we do deploy it for the staging now or we should wait for Lamdba version finished?

**Comment by ronaldtse** [comment]
@phuonghuynh let's deploy the Lambda version instead. We don't want to handle two Docker images, but we will need two separate databases for staging and production.

**Comment by maccraymer** [comment]
Any further progress on this? I will be meeting with the TC 211 Secretariat on Monday and need to report on this. Florian Esser has also agreed to continue the further development of the registry software. We need this staging instance to further test the operation of the Registry ASAP in order to compile a list of problems that need to be addressed in the next maintenance contract.

**Comment by phuonghuynh** [comment]
As discussed, we will use AWS Lambda for Staging & Production as well, however, I facing an issue of Spring Thymeleaf and Spring Container compatible issue with AWS Lambda Container, as error bellow. I think we can maintain 2 dockers for both prod & staging for now.
/cc @ronaldtse 

```
Caused by: java.lang.UnsupportedOperationException
	at com.amazonaws.serverless.proxy.internal.servlet.AwsServletContext.getNamedDispatcher(AwsServletContext.java:188)
...

```

**Comment by ronaldtse** [comment]
We already have a separate staging instance. Closing for now.
