### ISSUE TITLE
Unexpanded `${mail.baseUrl}` in password reset emails (production + staging)

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#25]
From @maccraymer 

> I requested a password reset but received an invalid URL via email for resetting the password (see below). I get the same error with the public registry. The `${mail.baseUrl}` variable was not expanded. I assume it should be
> `http://geodetic-staging.isotc211.org`
> for the staging Registry and
> `http://geodetic.isotc211.org`
> for the public Registry.
> 
> This error also occurs with email invitations for Control Body discussions.

The problem is `${mail.baseUrl}` is not expanded in email. @phuonghuynh could you confirm this is an issue with the staging and production instances, and get this fixed? Thanks!

**Comment by ronaldtse** [comment]
@phuonghuynh I believe this has been fixed?

**Comment by ronaldtse** [comment]
@phuonghuynh is this fixed? Thanks.

**Comment by phuonghuynh** [comment]
Yes, fixed , https://github.com/ISO-TC211/geodetic-registry-infra/blob/master/terraform-isoreg/terraform.tfstate#L896
