### ISSUE TITLE
Home Page deployment to AWS

### ISSUE THREAD

**Issue by phuonghuynh** [ISO-TC211/iso-geodetic-registry#28]
Implement Terraform module or AWS CloudFormation Stack for this one. Home Page also requires DB connection.

Related issue #27

**Comment by ronaldtse** [comment]
@phuonghuynh let's do Terraform if possible for simplicity!

**Comment by phuonghuynh** [comment]
Closed since we will move to lambda step by step, we will work on devops stuff later
