### ISSUE TITLE
Invalidated register items are not shown in item list

### ISSUE THREAD

**Issue by florianesser** [ISO-TC211/iso-geodetic-registry#70]
Register items that were invalidated are not shown in the list of contained items.

Reported by @maccraymer (item 2k)

**Comment by maccraymer** [comment]
I did not get an email notification for #71 that I assume addresses issues #70, 72, 74. Am I not supposed to?

Sent from my iPhone with autocorrect typos

On Mar 29, 2020, at 2:18 PM, phuong <notifications@github.com> wrote:

﻿

Closed #70<https://github.com/ISO-TC211/iso-geodetic-registry/issues/70> via #71<https://github.com/ISO-TC211/iso-geodetic-registry/pull/71>.

**Comment by florianesser** [comment]
@maccraymer You probably got a notification for #70 because I mentioned you there. I didn't mention you in #71.

If you'd like to get notifications for all issues in the repository, make sure to click the Watch button in the top right corner.
