### ISSUE TITLE
Pre-filling the successor item form for the Succeed action

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#82]
From @maccraymer :

This is the single most important thing we need as users of the Registry. Making corrections to existing Registry items is practically impossible without this. It simply takes far too long to manually copy/paste entries from the original item to the succeeding item just to correct one piece of information. The manual process is also prone to errors. I hope this enhancement will not be difficult to add. 

@florianesser would this be a software enhancement that you can probably do quickly?

**Comment by florianesser** [comment]
@maccraymer @ronaldtse I'll look into this tonight and let you know if there is a short-term solution. I have implemented that functionality in other installations (i.e. the [GDI-DE Registry](https://registry.gdi-de.org)) and think that a port to the Geodetic Registry will not be too hard.

**Comment by florianesser** [comment]
@ronaldtse @maccraymer I successfully ported the solution that I did for GDI-DE Registry. I'll create a PR once the change in registry-base is merged.
