### ISSUE TITLE
500 error in "Details action"

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#83]
From @maccraymer :

Selecting the Details action for proposals in the Submitting Organizations & Register Manager areas of the Registry management (after saving or after being returned by the CB) gives a HTTP Status 500 error. 

It works fine in the Control Body area. 

It’s not a big problem that the RM can’t view the proposal but it is for the Submitting Organization. If a proposal has an error and is sent back to the submitter for revision, the submitter can’t revise and resubmit it without the Details action working. 

I assume this is probably an implementation issue that Ribose needs to fix?

**Comment by ronaldtse** [comment]
@maccraymer we are attempting to fix this issue in #81 ,  will investigate and get back.

**Comment by florianesser** [comment]
@maccraymer @ronaldtse I'll take a look at this issue tonight. Will let you know what I find out here.

**Comment by florianesser** [comment]
@maccraymer @ronaldtse I've slightly modified and extended @phuonghuynh 's PR and submitted my changes as a new PR.

The changes should fix the HTTP 500 problem when opening the Details view for Supersessions. It will, however, not be possible to actually edit Supersessions that were e.g. returned to the submitter by the RM or CB. Allowing proper editing of saved, submitted or returned Supersessions will require some enhancements. I've opened the new issue #86 for that.

For the time being there is no way to edit a Supersession once it's been saved or submitted, the only way is to create a new Supersession. The upcoming prefill mechanism described in #82 hopefully makes that a bit less daunting.

**Comment by phuonghuynh** [comment]
@maccraymer @florianesser staging has been updated with this fix.

**Comment by maccraymer** [comment]
Thanks Florian and Phuong! Getting no 500 error now. Can this issue be closed?

**Comment by phuonghuynh** [comment]
Yes, we can close it
