### ISSUE TITLE
400 error with Safari when performing supercession

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#84]
From @maccraymer :

> It looks like there is stil a bug in the Registry (staging instance with Florian’s bug fixes) when using the supercession action. After entering the new information to supersede an item (vertical datum item 118 in my case), I get an “HTTP Status 400 - Bad Request“ error when submitting the new information.

> This is the single most important Registry function we need fixed as we are still unable to correct any existing information in the Registry database. We would greatly appreciate if you can fix this ASAP.

**Comment by ronaldtse** [comment]
As per @maccraymer , this bug only occurs on Safari, and works fine on Firefox / Chrome.

**Comment by phuonghuynh** [comment]
@maccraymer staging updated with this fix already
