### ISSUE TITLE
500 error in Clarify action

### ISSUE THREAD

**Issue by maccraymer** [ISO-TC211/iso-geodetic-registry#89]
Selecting the Clarify action for an item results in a "HTTP Status 500 - Internal Server Error". This bug is quite urgent to fix as I need to use this action to correct typos in the current Registry content for the Control Body meeting on Wed May 20.

**Comment by florianesser** [comment]
@phuonghuynh I've identified the issue and will submit a PR after https://github.com/ISO-TC211/registry-base/pull/12 is merged.

**Comment by phuonghuynh** [comment]
@florianesser merged
