### ISSUE TITLE
500 error in Details action after acceptance of clarification by RM

### ISSUE THREAD

**Issue by maccraymer** [ISO-TC211/iso-geodetic-registry#95]
Sorry for reporting another urgent bug.
After the Register Manager accepts a submitted clarification action for an item, the Details action for that item gives a HTTP Status 500 error in either the Submitting Organization, Register Manager or Control Body folders. No one is able to view the item's details once the RM accepts and the CB cannot evaluate the proposal. The Details action works before the RM accepts it.

**Comment by phuonghuynh** [comment]
@maccraymer @ronaldtse PR sent, #96 , waiting for review

**Comment by phuonghuynh** [comment]
@maccraymer staging deployed this fix, could you help to confirm?

**Comment by maccraymer** [comment]
Will do it now. Isn't it 2 am your time?

**Comment by maccraymer** [comment]
You are getting closer! The Details action after Register Manager acceptance now displays the item information but the links to the information sources (citations) on that page gives empty windows instead of the citation information.

**Comment by florianesser** [comment]
@maccraymer I couldn't reproduce that locally when doing a clarification on a Geodetic CRS. What item are you clarifying?

**Comment by maccraymer** [comment]
I was clarifying a vertical datum item (#140). It should be sitting in the Submitting Organization folder for the Control Body as being returned by the CB.

**Comment by maccraymer** [comment]
I'm working with the staging instance. I just resubmitted the proposal from the CB's Submitting Organization folder and accepted it in the Register Manager's folder. It's now in the CB's folder waiting for a decision. When I select the Details action from any of the folders, all looks okay and I get the item's information page but the information source links give a blank window. At previous steps in the above process, the information source links were correctly displaying the citations. it was only when the RM accepted the proposal did the link become blank. It occurs in both Safari and Chrome. I've left the proposal in the CB folder for you to check. DON'T APPROVE IT - SEND IT BACK TO THE SUBMITTER when done.

**Comment by maccraymer** [comment]
Same thing happens for a Geodetic CRS (item # 205: IGS08 - LatLonEHt). It's also sitting in the Control Body folder along with the Vertical Datum example (item # 140: Canadian Geodetic Vertical Datum of 2013 (Canadian Gravimetric Geoid of 2013a)).

**Comment by florianesser** [comment]
I don't think that I have a user in either the staging or the production instance.

**Comment by maccraymer** [comment]
I'll create one for you.

**Comment by maccraymer** [comment]
Created a CB user in the staging instance with all roles and Admin privileges. Will email you the login.

**Comment by florianesser** [comment]
Thanks, @maccraymer , I could reproduce it now and created a PR.

**Comment by maccraymer** [comment]
Thanks @florianesser! I guess there's no more time left in the contract so I greatly appreciate you following up on this!!
